#!/bin/bash
array=( "$@" )
file="${@: -1}"
unset "array[${#array[@]}-1]"
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
$ROOT_DIR/scripts/transpose "$file" | grep "${array[@]}" | $ROOT_DIR/scripts/transpose
