#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../lib";
use WbpsExpression::Model::Design;
use File::Slurp;

my $file = do {local $/ ; <>};
if(@ARGV){
  WbpsExpression::Model::Design::from_tsv(\$file)->to_tsv(@ARGV);
} else {
  my $tmp = "";
  WbpsExpression::Model::Design::from_tsv(\$file)->to_tsv(\$tmp);
  print $tmp;
}
