use strict;
use warnings;

use Test::More;
use Test::Mock::LWP;
use WbpsExpression::IncomingStudies::StudyMetadata::PubMedClient;

$Mock_ua->mock(get => sub {
  our (undef, $url) = @_;
  $Mock_response->mock(decoded_content => sub {local $/; <DATA>});
  return $Mock_response;
});


my $species = "schistosoma_mansoni";
my $pubmed_id = "29069413";

is_deeply(
  WbpsExpression::IncomingStudies::StudyMetadata::PubMedClient::title_and_description_for_pubmed_id($species, $pubmed_id),
  ["Lee .. Sternberg, 2018", "WormBase 2017: molting into a new stage. (Lee .. Sternberg, 2018)"],
  "Pick up paper from payload",
);

sub fix_species_variation {
   my ($species_ref, $species_in_title, $expected) = @_;
   $expected //= "<i>$species_in_title</i>";
   is(
     WbpsExpression::IncomingStudies::StudyMetadata::PubMedClient::italicise_species_in_title($species_ref, "prefix $species_in_title suffix"),
     "prefix $expected suffix",
     "$species_in_title -> $expected"
   );
}
fix_species_variation($species, "Schistosoma mansoni");
fix_species_variation($species, "schistosoma_mansoni");
fix_species_variation($species, "S mansoni");
fix_species_variation($species, "S. mansoni");
fix_species_variation($species, "<i>S. mansoni</i>", "<i>S. mansoni</i>");

done_testing();
__DATA__
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<pre>
&lt;PubmedArticle&gt;
    &lt;MedlineCitation Status="In-Data-Review" Owner="NLM"&gt;
        &lt;PMID Version="1"&gt;29069413&lt;/PMID&gt;
        &lt;DateRevised&gt;
            &lt;Year&gt;2019&lt;/Year&gt;
            &lt;Month&gt;04&lt;/Month&gt;
            &lt;Day&gt;26&lt;/Day&gt;
        &lt;/DateRevised&gt;
        &lt;Article PubModel="Print"&gt;
            &lt;Journal&gt;
                &lt;ISSN IssnType="Electronic"&gt;1362-4962&lt;/ISSN&gt;
                &lt;JournalIssue CitedMedium="Internet"&gt;
                    &lt;Volume&gt;46&lt;/Volume&gt;
                    &lt;Issue&gt;D1&lt;/Issue&gt;
                    &lt;PubDate&gt;
                        &lt;Year&gt;2018&lt;/Year&gt;
                        &lt;Month&gt;Jan&lt;/Month&gt;
                        &lt;Day&gt;04&lt;/Day&gt;
                    &lt;/PubDate&gt;
                &lt;/JournalIssue&gt;
                &lt;Title&gt;Nucleic acids research&lt;/Title&gt;
                &lt;ISOAbbreviation&gt;Nucleic Acids Res.&lt;/ISOAbbreviation&gt;
            &lt;/Journal&gt;
            &lt;ArticleTitle&gt;WormBase 2017: molting into a new stage.&lt;/ArticleTitle&gt;
            &lt;Pagination&gt;
                &lt;MedlinePgn&gt;D869-D874&lt;/MedlinePgn&gt;
            &lt;/Pagination&gt;
            &lt;ELocationID EIdType="doi" ValidYN="Y"&gt;10.1093/nar/gkx998&lt;/ELocationID&gt;
            &lt;Abstract&gt;
                &lt;AbstractText&gt;WormBase (http://www.wormbase.org) is an important knowledge resource for biomedical researchers worldwide. To accommodate the ever increasing amount and complexity of research data, WormBase continues to advance its practices on data acquisition, curation and retrieval to most effectively deliver comprehensive knowledge about Caenorhabditis elegans, and genomic information about other nematodes and parasitic flatworms. Recent notable enhancements include user-directed submission of data, such as micropublication; genomic data curation and presentation, including additional genomes and JBrowse, respectively; new query tools, such as SimpleMine, Gene Enrichment Analysis; new data displays, such as the Person Lineage browser and the Summary of Ontology-based Annotations. Anticipating more rapid data growth ahead, WormBase continues the process of migrating to a cutting-edge database technology to achieve better stability, scalability, reproducibility and a faster response time. To better serve the broader research community, WormBase, with five other Model Organism Databases and The Gene Ontology project, have begun to collaborate formally as the Alliance of Genome Resources.&lt;/AbstractText&gt;
                &lt;CopyrightInformation&gt;© The Author(s) 2017. Published by Oxford University Press on behalf of Nucleic Acids Research.&lt;/CopyrightInformation&gt;
            &lt;/Abstract&gt;
            &lt;AuthorList CompleteYN="Y"&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Lee&lt;/LastName&gt;
                    &lt;ForeName&gt;Raymond Y N&lt;/ForeName&gt;
                    &lt;Initials&gt;RYN&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Howe&lt;/LastName&gt;
                    &lt;ForeName&gt;Kevin L&lt;/ForeName&gt;
                    &lt;Initials&gt;KL&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Harris&lt;/LastName&gt;
                    &lt;ForeName&gt;Todd W&lt;/ForeName&gt;
                    &lt;Initials&gt;TW&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Arnaboldi&lt;/LastName&gt;
                    &lt;ForeName&gt;Valerio&lt;/ForeName&gt;
                    &lt;Initials&gt;V&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Cain&lt;/LastName&gt;
                    &lt;ForeName&gt;Scott&lt;/ForeName&gt;
                    &lt;Initials&gt;S&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Chan&lt;/LastName&gt;
                    &lt;ForeName&gt;Juancarlos&lt;/ForeName&gt;
                    &lt;Initials&gt;J&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Chen&lt;/LastName&gt;
                    &lt;ForeName&gt;Wen J&lt;/ForeName&gt;
                    &lt;Initials&gt;WJ&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Davis&lt;/LastName&gt;
                    &lt;ForeName&gt;Paul&lt;/ForeName&gt;
                    &lt;Initials&gt;P&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Gao&lt;/LastName&gt;
                    &lt;ForeName&gt;Sibyl&lt;/ForeName&gt;
                    &lt;Initials&gt;S&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Grove&lt;/LastName&gt;
                    &lt;ForeName&gt;Christian&lt;/ForeName&gt;
                    &lt;Initials&gt;C&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Kishore&lt;/LastName&gt;
                    &lt;ForeName&gt;Ranjana&lt;/ForeName&gt;
                    &lt;Initials&gt;R&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Muller&lt;/LastName&gt;
                    &lt;ForeName&gt;Hans-Michael&lt;/ForeName&gt;
                    &lt;Initials&gt;HM&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Nakamura&lt;/LastName&gt;
                    &lt;ForeName&gt;Cecilia&lt;/ForeName&gt;
                    &lt;Initials&gt;C&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Nuin&lt;/LastName&gt;
                    &lt;ForeName&gt;Paulo&lt;/ForeName&gt;
                    &lt;Initials&gt;P&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Paulini&lt;/LastName&gt;
                    &lt;ForeName&gt;Michael&lt;/ForeName&gt;
                    &lt;Initials&gt;M&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Raciti&lt;/LastName&gt;
                    &lt;ForeName&gt;Daniela&lt;/ForeName&gt;
                    &lt;Initials&gt;D&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Rodgers&lt;/LastName&gt;
                    &lt;ForeName&gt;Faye&lt;/ForeName&gt;
                    &lt;Initials&gt;F&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Wellcome Trust Sanger Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SA, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Russell&lt;/LastName&gt;
                    &lt;ForeName&gt;Matt&lt;/ForeName&gt;
                    &lt;Initials&gt;M&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Schindelman&lt;/LastName&gt;
                    &lt;ForeName&gt;Gary&lt;/ForeName&gt;
                    &lt;Initials&gt;G&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Tuli&lt;/LastName&gt;
                    &lt;ForeName&gt;Mary Ann&lt;/ForeName&gt;
                    &lt;Initials&gt;MA&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Van Auken&lt;/LastName&gt;
                    &lt;ForeName&gt;Kimberly&lt;/ForeName&gt;
                    &lt;Initials&gt;K&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Wang&lt;/LastName&gt;
                    &lt;ForeName&gt;Qinghua&lt;/ForeName&gt;
                    &lt;Initials&gt;Q&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Williams&lt;/LastName&gt;
                    &lt;ForeName&gt;Gary&lt;/ForeName&gt;
                    &lt;Initials&gt;G&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Wright&lt;/LastName&gt;
                    &lt;ForeName&gt;Adam&lt;/ForeName&gt;
                    &lt;Initials&gt;A&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Yook&lt;/LastName&gt;
                    &lt;ForeName&gt;Karen&lt;/ForeName&gt;
                    &lt;Initials&gt;K&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Berriman&lt;/LastName&gt;
                    &lt;ForeName&gt;Matthew&lt;/ForeName&gt;
                    &lt;Initials&gt;M&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Wellcome Trust Sanger Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SA, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Kersey&lt;/LastName&gt;
                    &lt;ForeName&gt;Paul&lt;/ForeName&gt;
                    &lt;Initials&gt;P&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;European Molecular Biology Laboratory, European Bioinformatics Institute, Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD, UK.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Schedl&lt;/LastName&gt;
                    &lt;ForeName&gt;Tim&lt;/ForeName&gt;
                    &lt;Initials&gt;T&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Department of Genetics, Washington University School of Medicine, St Louis, MO 63110, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Stein&lt;/LastName&gt;
                    &lt;ForeName&gt;Lincoln&lt;/ForeName&gt;
                    &lt;Initials&gt;L&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Informatics and Bio-computing Platform, Ontario Institute for Cancer Research, Toronto, ON M5G0A3, Canada.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
                &lt;Author ValidYN="Y"&gt;
                    &lt;LastName&gt;Sternberg&lt;/LastName&gt;
                    &lt;ForeName&gt;Paul W&lt;/ForeName&gt;
                    &lt;Initials&gt;PW&lt;/Initials&gt;
                    &lt;AffiliationInfo&gt;
                        &lt;Affiliation&gt;Division of Biology and Biological Engineering 156-29, California Institute of Technology, Pasadena, CA 91125, USA.&lt;/Affiliation&gt;
                    &lt;/AffiliationInfo&gt;
                &lt;/Author&gt;
            &lt;/AuthorList&gt;
            &lt;Language&gt;eng&lt;/Language&gt;
            &lt;GrantList CompleteYN="Y"&gt;
                &lt;Grant&gt;
                    &lt;GrantID&gt;MR/L001020/1&lt;/GrantID&gt;
                    &lt;Agency&gt;Medical Research Council&lt;/Agency&gt;
                    &lt;Country&gt;United Kingdom&lt;/Country&gt;
                &lt;/Grant&gt;
                &lt;Grant&gt;
                    &lt;GrantID&gt;U01 LM012672&lt;/GrantID&gt;
                    &lt;Acronym&gt;LM&lt;/Acronym&gt;
                    &lt;Agency&gt;NLM NIH HHS&lt;/Agency&gt;
                    &lt;Country&gt;United States&lt;/Country&gt;
                &lt;/Grant&gt;
                &lt;Grant&gt;
                    &lt;GrantID&gt;U24 HG002223&lt;/GrantID&gt;
                    &lt;Acronym&gt;HG&lt;/Acronym&gt;
                    &lt;Agency&gt;NHGRI NIH HHS&lt;/Agency&gt;
                    &lt;Country&gt;United States&lt;/Country&gt;
                &lt;/Grant&gt;
                &lt;Grant&gt;
                    &lt;GrantID&gt;U41 HG002223&lt;/GrantID&gt;
                    &lt;Acronym&gt;HG&lt;/Acronym&gt;
                    &lt;Agency&gt;NHGRI NIH HHS&lt;/Agency&gt;
                    &lt;Country&gt;United States&lt;/Country&gt;
                &lt;/Grant&gt;
            &lt;/GrantList&gt;
            &lt;PublicationTypeList&gt;
                &lt;PublicationType UI="D016428"&gt;Journal Article&lt;/PublicationType&gt;
            &lt;/PublicationTypeList&gt;
        &lt;/Article&gt;
        &lt;MedlineJournalInfo&gt;
            &lt;Country&gt;England&lt;/Country&gt;
            &lt;MedlineTA&gt;Nucleic Acids Res&lt;/MedlineTA&gt;
            &lt;NlmUniqueID&gt;0411011&lt;/NlmUniqueID&gt;
            &lt;ISSNLinking&gt;0305-1048&lt;/ISSNLinking&gt;
        &lt;/MedlineJournalInfo&gt;
    &lt;/MedlineCitation&gt;
    &lt;PubmedData&gt;
        &lt;History&gt;
            &lt;PubMedPubDate PubStatus="received"&gt;
                &lt;Year&gt;2017&lt;/Year&gt;
                &lt;Month&gt;09&lt;/Month&gt;
                &lt;Day&gt;29&lt;/Day&gt;
            &lt;/PubMedPubDate&gt;
            &lt;PubMedPubDate PubStatus="accepted"&gt;
                &lt;Year&gt;2017&lt;/Year&gt;
                &lt;Month&gt;10&lt;/Month&gt;
                &lt;Day&gt;11&lt;/Day&gt;
            &lt;/PubMedPubDate&gt;
            &lt;PubMedPubDate PubStatus="pubmed"&gt;
                &lt;Year&gt;2017&lt;/Year&gt;
                &lt;Month&gt;10&lt;/Month&gt;
                &lt;Day&gt;27&lt;/Day&gt;
                &lt;Hour&gt;6&lt;/Hour&gt;
                &lt;Minute&gt;0&lt;/Minute&gt;
            &lt;/PubMedPubDate&gt;
            &lt;PubMedPubDate PubStatus="medline"&gt;
                &lt;Year&gt;2017&lt;/Year&gt;
                &lt;Month&gt;10&lt;/Month&gt;
                &lt;Day&gt;27&lt;/Day&gt;
                &lt;Hour&gt;6&lt;/Hour&gt;
                &lt;Minute&gt;0&lt;/Minute&gt;
            &lt;/PubMedPubDate&gt;
            &lt;PubMedPubDate PubStatus="entrez"&gt;
                &lt;Year&gt;2017&lt;/Year&gt;
                &lt;Month&gt;10&lt;/Month&gt;
                &lt;Day&gt;26&lt;/Day&gt;
                &lt;Hour&gt;6&lt;/Hour&gt;
                &lt;Minute&gt;0&lt;/Minute&gt;
            &lt;/PubMedPubDate&gt;
        &lt;/History&gt;
        &lt;PublicationStatus&gt;ppublish&lt;/PublicationStatus&gt;
        &lt;ArticleIdList&gt;
            &lt;ArticleId IdType="pubmed"&gt;29069413&lt;/ArticleId&gt;
            &lt;ArticleId IdType="pii"&gt;4563314&lt;/ArticleId&gt;
            &lt;ArticleId IdType="doi"&gt;10.1093/nar/gkx998&lt;/ArticleId&gt;
            &lt;ArticleId IdType="pmc"&gt;PMC5753391&lt;/ArticleId&gt;
        &lt;/ArticleIdList&gt;
        &lt;ReferenceList&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Nucleic Acids Res. 2016 Jan 4;44(D1):D774-80&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;26578572&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;BMC Bioinformatics. 2011 Dec 14;12 Suppl 14:S2&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;22373417&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Genome Res. 2002 Oct;12(10):1599-610&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;12368253&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Mamm Genome. 2015 Oct;26(9-10):584-9&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;26093607&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Nat Commun. 2016 Feb 01;7:10513&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;26830005&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;PLoS Genet. 2011 Jul;7(7):e1002174&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;21779179&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Genome Biol. 2016 Jun 10;17 (1):124&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;27286965&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Nucleic Acids Res. 2017 Jan 4;45(D1):D650-D657&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;27701074&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Genome Res. 2009 Feb;19(2):327-35&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;19029536&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Genome Biol. 2016 Apr 12;17 :66&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;27072794&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;BMC Bioinformatics. 2016 Sep 13;17 (1):366&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;27618863&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Mol Biochem Parasitol. 2017 Jul;215:2-10&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;27899279&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Nature. 2009 Jun 18;459(7249):927-30&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;19536255&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Worm. 2012 Jan 1;1(1):15-21&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;24058818&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;PLoS Biol. 2003 Nov;1(2):E45&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;14624247&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Nucleic Acids Res. 2015 Jan;43(Database issue):D789-98&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;25428349&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
            &lt;Reference&gt;
                &lt;Citation&gt;Sci Rep. 2013;3:1802&lt;/Citation&gt;
                &lt;ArticleIdList&gt;
                    &lt;ArticleId IdType="pubmed"&gt;23652793&lt;/ArticleId&gt;
                &lt;/ArticleIdList&gt;
            &lt;/Reference&gt;
        &lt;/ReferenceList&gt;
    &lt;/PubmedData&gt;
&lt;/PubmedArticle&gt;

</pre>
